export const CALL_API_REGISTER = 'CALL_API_REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const ERROR_SERVER = 'ERROR_SERVER';
export const CALL_API_LOGIN = "CALL_API_LOGIN";
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';