//user-info
export const GET_USER = "GET_USER";
export const UPDATE_USER = "UPDATE_USER";

export const CALL_API_REGISTER = 'CALL_API_REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const ERROR_SERVER = 'ERROR_SERVER';
export const CALL_API_LOGIN = "CALL_API_LOGIN";
export const CALL_API_LOGIN_FB = "CALL_API_LOGIN_FB";
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const ADD_FRIEND = "ADD_FRIEND";
export const REMOVE_FRIEND = "REMOVE_FRIEND";
export const CANCEL_CONTACTS_SENT = 'CANCEL_CONTACTS_SENT';
export const SETUP_SOCKET ='SETUP_SOCKET';
export const RES_ADD_NEW_CONTACT = 'RES_ADD_NEW_CONTACT';
export const RES_REMOVE_NEW_CONTACT = 'RES_REMOVE_NEW_CONTACT';
export const RESET_NOTIFI = 'RESET_NOTIFI';
export const MARK_ALL_READ = 'MARK_ALL_READ';

//list contacts
export const GET_LIST_CONTACTS = "GET_LIST_CONTACTS";
export const ADD_LIST_CONTACTS = "ADD_LIST_CONTACTS";
export const SCROLL_LIST_CONTACTS = "SCROLL_LIST_CONTACTS";
export const REMOVE_LIST_CONTACTS = "REMOVE_LIST_CONTACTS";
export const GET_LIST_CONTACTS_SENT = "GET_LIST_CONTACTS_SENT";
export const ADD_LIST_CONTACTS_SENT = "ADD_LIST_CONTACTS_SENT";
export const SCROLL_LIST_CONTACTS_SENT = "SCROLL_LIST_CONTACTS_SENT";
export const REMOVE_LIST_CONTACTS_SENT = "REMOVE_LIST_CONTACTS_SENT"
export const GET_LIST_CONTACTS_RECEIVED = "GET_LIST_CONTACTS_RECEIVED";
export const ADD_LIST_CONTACTS_RECEIVED = "ADD_LIST_CONTACTS_RECEIVED";
export const SCROLL_LIST_CONTACTS_RECEIVED = "SCROLL_LIST_CONTACTS_RECEIVED";
export const REMOVE_LIST_CONTACTS_RECEIVED = "REMOVE_LIST_CONTACTS_RECEIVED";
//count contacts
export const COUNT_LIST_CONTACTS = "COUNT_LIST_CONTACTS";
export const ADD_COUNT_LIST_CONTACTS = "ADD_COUNT_LIST_CONTACTS";
export const REMOVE_COUNT_LIST_CONTACTS = "REMOVE_COUNT_LIST_CONTACTS";
export const COUNT_LIST_CONTACTS_SENT = "COUNT_LIST_CONTACTS_SENT";
export const ADD_COUNT_LIST_CONTACTS_SENT = "ADD_COUNT_LIST_CONTACTS_SENT";
export const REMOVE_COUNT_LIST_CONTACTS_SENT = "REMOVE_COUNT_LIST_CONTACTS_SENT"
export const COUNT_LIST_CONTACTS_RECEIVED = "COUNT_LIST_CONTACTS_RECEIVED";
export const ADD_COUNT_LIST_CONTACTS_RECEIVED = "ADD_COUNT_LIST_CONTACTS_RECEIVED";
export const REMOVE_COUNT_LIST_CONTACTS_RECEIVED = "REMOVE_COUNT_LIST_CONTACTS_RECEIVED";

//conversation-message
export const GET_LIST_USER_CONVERSATIONS = "GET_LIST_USER_CONVERSATIONS";
export const ADD_LIST_USER_CONVERSATIONS = "ADD_LIST_USER_CONVERSATIONS";
export const CHANGE_LIST_USER_CONVERSATIONS = "CHANGE_LIST_USER_CONVERSATIONS";
export const REMOVE_LIST_USER_CONVERSATIONS = "REMOVE_LIST_USER_CONVERSATIONS";
export const SCROLL_LIST_USER_CONVERSATIONS = "SCROLL_LIST_USER_CONVERSATIONS";

export const GET_LIST_GROUP_CONVERSATIONS = "GET_LIST_GROUP_CONVERSATIONS";
export const ADD_LIST_GROUP_CONVERSATIONS = "ADD_LIST_GROUP_CONVERSATIONS";
export const CHANGE_LIST_GROUP_CONVERSATIONS = "CHANGE_LIST_GROUP_CONVERSATIONS";
export const REMOVE_LIST_GROUP_CONVERSATIONS = "REMOVE_LIST_GROUP_CONVERSATIONS";
export const SCROLL_LIST_GROUP_CONVERSATIONS = "SCROLL_LIST_GROUP_CONVERSATIONS";

export const GET_LIST_ALL_CONVERSATIONS = "GET_LIST_ALL_CONVERSATIONS";
export const ADD_LIST_ALL_CONVERSATIONS = "ADD_LIST_ALL_CONVERSATIONS";
export const CHANGE_LIST_ALL_CONVERSATIONS = "CHANGE_LIST_ALL_CONVERSATIONS";
export const REMOVE_LIST_ALL_CONVERSATIONS = "REMOVE_LIST_ALL_CONVERSATIONS";
export const SCROLL_LIST_ALL_CONVERSATIONS = "SCROLL_LIST_ALL_CONVERSATIONS";

//other change check list
export const CHECK_CHANGE_LIST_MESSAGE= "CHECK_CHANGE_LIST_MESSAGE"
//chat
export const ADD_ON_MESSAGE = "ADD_ON_MESSAGE";
export const REMOVE_ON_MESSAGE = "REMOVE_ON_MESSAGE";
export const ADD_ON_TYPING = "ADD_ON_TYPING";
export const REMOVE_ON_TYPING = "REMOVE_ON_TYPING";

//video chat
export const OPEN_MODAL_CALLER = "OPEN_MODAL_CALLER";
export const CLOSE_MODAL_CALLER = "CLOSE_MODAL_CALLER";
export const OPEN_MODAL_LISTENER = "OPEN_MODAL_LISTENER";
export const CLOSE_MODAL_LISTENER = "CLOSE_MODAL_LISTENER"

//stream
export const OPEN_MODAL_STREAM = "OPEN_MODAL_STREAM";
export const CLOSE_MODAL_STREAM = "CLOSE_MODAL_STREAM"

//ice turn server
export const GET_ICE_TURN_SERVER = "GET_ICE_TURN_SERVER"

//online-offline
export const SET_USER_ONLINE = "SET_USER_ONLINE";
export const REMOVE_ONLINE = "REMOVE_ONLINE"