export const CALL_API_REGISTER = 'CALL_API_REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const ERROR_SERVER = 'ERROR_SERVER';
export const CALL_API_LOGIN = "CALL_API_LOGIN";
export const CALL_API_LOGIN_FB = "CALL_API_LOGIN_FB";
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const ADD_FRIEND = "ADD_FRIEND";
export const REMOVE_FRIEND = "REMOVE_FRIEND";
export const CANCEL_CONTACTS_SENT = 'CANCEL_CONTACTS_SENT';
export const SETUP_SOCKET ='SETUP_SOCKET';
export const RES_ADD_NEW_CONTACT = 'RES_ADD_NEW_CONTACT';
export const RES_REMOVE_NEW_CONTACT = 'RES_REMOVE_NEW_CONTACT';
export const RESET_NOTIFI = 'RESET_NOTIFI';
export const MARK_ALL_READ = 'MARK_ALL_READ';

//list contacts
export const GET_LIST_CONTACTS = "GET_LIST_CONTACTS";
export const ADD_LIST_CONTACTS = "ADD_LIST_CONTACTS";
export const SCROLL_LIST_CONTACTS = "SCROLL_LIST_CONTACTS";
export const REMOVE_LIST_CONTACTS = "REMOVE_LIST_CONTACTS";
export const GET_LIST_CONTACTS_SENT = "GET_LIST_CONTACTS_SENT";
export const ADD_LIST_CONTACTS_SENT = "ADD_LIST_CONTACTS_SENT";
export const SCROLL_LIST_CONTACTS_SENT = "SCROLL_LIST_CONTACTS_SENT";
export const REMOVE_LIST_CONTACTS_SENT = "REMOVE_LIST_CONTACTS_SENT"
export const GET_LIST_CONTACTS_RECEIVED = "GET_LIST_CONTACTS_RECEIVED";
export const ADD_LIST_CONTACTS_RECEIVED = "ADD_LIST_CONTACTS_RECEIVED";
export const SCROLL_LIST_CONTACTS_RECEIVED = "SCROLL_LIST_CONTACTS_RECEIVED";
export const REMOVE_LIST_CONTACTS_RECEIVED = "REMOVE_LIST_CONTACTS_RECEIVED";
//count contacts
export const COUNT_LIST_CONTACTS = "COUNT_LIST_CONTACTS";
export const ADD_COUNT_LIST_CONTACTS = "ADD_COUNT_LIST_CONTACTS";
export const REMOVE_COUNT_LIST_CONTACTS = "REMOVE_COUNT_LIST_CONTACTS";
export const COUNT_LIST_CONTACTS_SENT = "COUNT_LIST_CONTACTS_SENT";
export const ADD_COUNT_LIST_CONTACTS_SENT = "ADD_COUNT_LIST_CONTACTS_SENT";
export const REMOVE_COUNT_LIST_CONTACTS_SENT = "REMOVE_COUNT_LIST_CONTACTS_SENT"
export const COUNT_LIST_CONTACTS_RECEIVED = "COUNT_LIST_CONTACTS_RECEIVED";
export const ADD_COUNT_LIST_CONTACTS_RECEIVED = "ADD_COUNT_LIST_CONTACTS_RECEIVED";
export const REMOVE_COUNT_LIST_CONTACTS_RECEIVED = "REMOVE_COUNT_LIST_CONTACTS_RECEIVED";

